server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: client
          uri: http://localhost:8081
          predicates:
            - Path=/clientSystems/** 
        - id: channel
          uri: http://localhost:8082
          predicates:
            - Path=/channelSystems/** 
        - id: video
          uri: http://localhost:8083
          predicates:
            - Path=/videoServices/** 
        - id: policy
          uri: http://localhost:8084
          predicates:
            - Path=/policyManagements/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: client
          uri: http://client:8080
          predicates:
            - Path=/clientSystems/** 
        - id: channel
          uri: http://channel:8080
          predicates:
            - Path=/channelSystems/** 
        - id: video
          uri: http://video:8080
          predicates:
            - Path=/videoServices/** 
        - id: policy
          uri: http://policy:8080
          predicates:
            - Path=/policyManagements/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
